/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_amytech_android_framework_api_APIList */

#ifndef _Included_com_amytech_android_framework_api_APIList
#define _Included_com_amytech_android_framework_api_APIList
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_amytech_android_framework_api_APIList
 * Method:    getAPPID
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_amytech_android_framework_api_APIList_getAPPID
  (JNIEnv *, jobject);

/*
 * Class:     com_amytech_android_framework_api_APIList
 * Method:    getAppSecret
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_amytech_android_framework_api_APIList_getAppSecret
  (JNIEnv *, jobject);

/*
 * Class:     com_amytech_android_framework_api_APIList
 * Method:    URL_TMALL_STYLE
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_amytech_android_framework_api_APIList_URL_1TMALL_1STYLE
  (JNIEnv *, jobject);

/*
 * Class:     com_amytech_android_framework_api_APIList
 * Method:    URL_TMALL_LIST
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_amytech_android_framework_api_APIList_URL_1TMALL_1LIST
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
